bio:
  # 项目 的 根目录
  rootPath: E:/bioResp
  # 用户上传文件 的 存储地址
  uploadPath: E:/bioResp/upload/
  # 啊啊啊啊
  transPath: E:/bioResp/result/genResult/
  # 脚本生成的结果 的 存储地址
  genPath: http://127.0.0.1:8887/result/genResult/
  # draftBlast 的 脚本的位置
  draftPath: E:/bioResp/exec/simulatedServer/draftBlast.py
  # fill的脚本位置
  fillPath: E:/bioResp/exec/simulatedServer/quartet_gapfill_server.py
  # telo的脚本位置
  teloPath: E:/bioResp/exec/simulatedServer/quartet_telo_server.py
  # 脚本 的 启动方式 (Java/python/perl...)
  exeMethod: python



---
server:
  port: 8080

---
# 设置session的过期时间为120min 过了120min后自动销毁session
server:
  servlet:
    session:
      timeout: 120

---

# mail配置
spring:
  mail:
    host: smtp.qq.com
    username: 123456@qq.com # 发给谁 需要用自己的qq设置
    password: abcdef # 授权码
    port: 587 # 端口号
    default-encoding: utf-8
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  datasource:
    url: jdbc:mysql://localhost:3306/bio_info?rewriteBatchedStatements=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200102
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      async-init: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.SlowSqlMills=5000
      # 监控后台的配置，如登录账号和密码等
      monitor:
        allow: 127.0.0.1
        loginUsername: admin
        loginPassword: admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




